### ISSUE TITLE
Annotations: Add API for "DS"

### ISSUE THREAD

**Issue by jamie-lemon** [ArtifexSoftware/mupdf.js#43] opened 2024-03-20 23:02 UTC
We can extract required information for color and alignment from a text item from the "DS" property.

![image](https://github.com/ArtifexSoftware/mupdf.js/assets/107279992/0019da17-1db3-4413-bff2-33485abfaebe)

Can we expose a get/set API for this?

**Comment by ccxvii** [comment] 2024-08-13 15:40
Duplicate of #28.

**Closed by ccxvii** 2024-08-13 15:40 UTC
Labels: core-api, annotations
